version: '3'

services:
  frontend:
    image: abhijjainn/yovo-frontend-image:latest
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - yovo-network

  backend:
    image: abhijjainn/yovo-backend-image:latest
    ports:
      - "5000:5000"
    restart: always
    networks:
      - yovo-network
      
networks:
  yovo-network:
    driver: bridge